/**
 * NSE-listed equities (Nifty 200 representative universe).
 * Yahoo Finance uses .NS suffix — applied automatically at fetch time.
 */

export const NSE_TICKERS = [
  // Nifty 50
  'RELIANCE', 'TCS', 'HDFCBANK', 'INFY', 'ICICIBANK', 'HINDUNILVR', 'ITC', 'SBIN', 'BHARTIARTL', 'KOTAKBANK',
  'LT', 'BAJFINANCE', 'ASIANPAINT', 'AXISBANK', 'MARUTI', 'TITAN', 'SUNPHARMA', 'NTPC', 'ONGC', 'TATAMOTORS',
  'POWERGRID', 'M&M', 'WIPRO', 'ULTRACEMCO', 'HCLTECH', 'TATASTEEL', 'ADANIENT', 'ADANIPORTS', 'COALINDIA', 'JSWSTEEL',
  'INDUSINDBK', 'GRASIM', 'DRREDDY', 'CIPLA', 'APOLLOHOSP', 'EICHERMOT', 'BRITANNIA', 'DIVISLAB', 'HEROMOTOCO', 'BPCL',
  'TATACONSUM', 'HINDALCO', 'SBILIFE', 'BAJAJFINSV', 'TECHM', 'NESTLEIND', 'HDFCLIFE', 'VEDL', 'PIDILITIND', 'LTIM',
  // Nifty Next 50
  'ADANIGREEN', 'ADANIPOWER', 'AMBUJACEM', 'AUROPHARMA', 'BANKBARODA', 'BERGEPAINT', 'BOSCHLTD', 'CANBK', 'CHOLAFIN', 'COLPAL',
  'DABUR', 'DLF', 'GAIL', 'GODREJCP', 'HAVELLS', 'HDFCAMC', 'ICICIPRULI', 'ICICIGI', 'INDIGO', 'IOC',
  'JINDALSTEL', 'JIOFIN', 'LICI', 'LUPIN', 'MARICO', 'MOTHERSON', 'NAUKRI', 'PFC', 'PNB', 'RECLTD',
  'SHREECEM', 'SIEMENS', 'SRF', 'TATAPOWER', 'TORNTPHARM', 'TRENT', 'TVSMOTOR', 'UBL', 'UNIONBANK', 'VBL',
  'VOLTAS', 'ZOMATO', 'ZYDUSLIFE', 'ABB', 'ACC', 'BEL', 'HAL', 'IRCTC', 'MANKIND', 'MAXHEALTH',
  // Additional liquid NSE names
  'ABBOTINDIA', 'ALKEM', 'ASHOKLEY', 'ASTRAL', 'ATGL', 'BALKRISIND', 'BANDHANBNK', 'BATAINDIA', 'BIOCON', 'BHEL',
  'CUMMINSIND', 'DALBHARAT', 'DEEPAKNTR', 'DIXON', 'ESCORTS', 'EXIDEIND', 'FEDERALBNK', 'GLENMARK', 'GMRINFRA', 'GODREJPROP',
  'HINDPETRO', 'HONAUT', 'IDFCFIRSTB', 'IEX', 'IGL', 'INDHOTEL', 'INDUSTOWER', 'IRB', 'JUBLFOOD', 'KALYANKJIL',
  'KEI', 'KPITTECH', 'LAURUSLABS', 'LICHSGFIN', 'LODHA', 'M&MFIN', 'MFSL', 'MGL', 'MPHASIS', 'MRF',
  'NHPC', 'NMDC', 'OBEROIRLTY', 'OFSS', 'OIL', 'PAGEIND', 'PAYTM', 'PERSISTENT', 'PETRONET', 'PHOENIXLTD',
  'PIIND', 'POLYCAB', 'PRESTIGE', 'RAMCOCEM', 'SAIL', 'SANOFI', 'SCHAEFFLER', 'SHRIRAMFIN', 'SONACOMS', 'STARHEALTH',
  'SUPREMEIND', 'SUZLON', 'SYNGENE', 'TATACHEM', 'TATACOMM', 'TATAELXSI', 'THERMAX', 'TIINDIA', 'TORNTPOWER', 'UPL',
  'WHIRLPOOL', 'YESBANK', 'ZEEL', 'AUBANK', 'AARTIIND', 'ABCAPITAL', 'APLAPOLLO', 'AWL', 'BSE', 'CDSL',
  'CROMPTON', 'CONCOR', 'COROMANDEL', 'CUB', 'DELHIVERY', 'DEVYANI', 'FACT', 'FORTIS', 'GLAND', 'GICRE',
  'GUJGASLTD', 'HAPPSTMNDS', 'HATSUN', 'HINDZINC', 'IDBI', 'INTELLECT', 'IPCALAB', 'JKCEMENT', 'JSWENERGY', 'KAJARIACER',
  'KANSAINER', 'KAYNES', 'KPRMILL', 'LALPATHLAB', 'MANYAVAR', 'METROPOLIS', 'MOTILALOFS', 'MRPL', 'NAM-INDIA', 'NATCOPHARM',
  'NAVINFLUOR', 'NETWORK18', 'NYKAA', 'PCBL', 'POLICYBZR', 'POONAWALLA', 'RADICO', 'RAIN', 'RATNAMANI', 'REDINGTON',
  'ROUTE', 'RVNL', 'SAREGAMA', 'SCI', 'SHYAMMETL', 'SKFINDIA', 'SOBHA', 'SOLARINDS', 'SUMICHEM', 'SUNTV',
  'TANLA', 'TATATECH', 'TEJASNET', 'TIMKEN', 'TRIDENT', 'TTML', 'UTIAMC', 'VARUNBEV', 'VIJAYA', 'WELCORP',
  'WOCKPHARMA', 'YESBANK',
];

/** Benchmark index ticker for sector-relative / beta context (not scanned as equity) */
export const NSE_BENCHMARK = '^NSEI';
