/** NSE ticker → sector mapping */

export const INDIA_TICKER_SECTORS = {
  RELIANCE: 'Energy',
  ONGC: 'Energy',
  BPCL: 'Energy',
  IOC: 'Energy',
  GAIL: 'Energy',
  OIL: 'Energy',
  PETRONET: 'Energy',
  ADANIGREEN: 'Energy',
  ADANIPOWER: 'Energy',
  TATAPOWER: 'Energy',
  NTPC: 'Utilities',
  POWERGRID: 'Utilities',
  NHPC: 'Utilities',
  TORNTPOWER: 'Utilities',
  TCS: 'Technology',
  INFY: 'Technology',
  HCLTECH: 'Technology',
  WIPRO: 'Technology',
  TECHM: 'Technology',
  LTIM: 'Technology',
  MPHASIS: 'Technology',
  PERSISTENT: 'Technology',
  COFORGE: 'Technology',
  KPITTECH: 'Technology',
  TATAELXSI: 'Technology',
  OFSS: 'Technology',
  TATATECH: 'Technology',
  HDFCBANK: 'Financials',
  ICICIBANK: 'Financials',
  KOTAKBANK: 'Financials',
  AXISBANK: 'Financials',
  SBIN: 'Financials',
  INDUSINDBK: 'Financials',
  BAJFINANCE: 'Financials',
  BAJAJFINSV: 'Financials',
  HDFCLIFE: 'Financials',
  SBILIFE: 'Financials',
  ICICIPRULI: 'Financials',
  ICICIGI: 'Financials',
  LICI: 'Financials',
  SHRIRAMFIN: 'Financials',
  CHOLAFIN: 'Financials',
  PFC: 'Financials',
  RECLTD: 'Financials',
  BANKBARODA: 'Financials',
  CANBK: 'Financials',
  PNB: 'Financials',
  FEDERALBNK: 'Financials',
  IDFCFIRSTB: 'Financials',
  BANDHANBNK: 'Financials',
  AUBANK: 'Financials',
  HDFCAMC: 'Financials',
  SUNPHARMA: 'Healthcare',
  DRREDDY: 'Healthcare',
  CIPLA: 'Healthcare',
  DIVISLAB: 'Healthcare',
  APOLLOHOSP: 'Healthcare',
  LUPIN: 'Healthcare',
  ZYDUSLIFE: 'Healthcare',
  AUROPHARMA: 'Healthcare',
  BIOCON: 'Healthcare',
  TORONTPHARM: 'Healthcare',
  ALKEM: 'Healthcare',
  MANKIND: 'Healthcare',
  MAXHEALTH: 'Healthcare',
  MARUTI: 'Consumer Disc.',
  TATAMOTORS: 'Consumer Disc.',
  'M&M': 'Consumer Disc.',
  EICHERMOT: 'Consumer Disc.',
  HEROMOTOCO: 'Consumer Disc.',
  'BAJAJ-AUTO': 'Consumer Disc.',
  TVSMOTOR: 'Consumer Disc.',
  TITAN: 'Consumer Disc.',
  TRENT: 'Consumer Disc.',
  ASIANPAINT: 'Consumer Disc.',
  HINDUNILVR: 'Consumer Staples',
  ITC: 'Consumer Staples',
  NESTLEIND: 'Consumer Staples',
  BRITANNIA: 'Consumer Staples',
  TATACONSUM: 'Consumer Staples',
  DABUR: 'Consumer Staples',
  MARICO: 'Consumer Staples',
  GODREJCP: 'Consumer Staples',
  COLPAL: 'Consumer Staples',
  UBL: 'Consumer Staples',
  VBL: 'Consumer Staples',
  LT: 'Industrials',
  BEL: 'Industrials',
  HAL: 'Industrials',
  SIEMENS: 'Industrials',
  ABB: 'Industrials',
  BHEL: 'Industrials',
  CUMMINSIND: 'Industrials',
  TATASTEEL: 'Materials',
  JSWSTEEL: 'Materials',
  HINDALCO: 'Materials',
  VEDL: 'Materials',
  COALINDIA: 'Materials',
  SAIL: 'Materials',
  ULTRACEMCO: 'Materials',
  GRASIM: 'Materials',
  SHREECEM: 'Materials',
  AMBUJACEM: 'Materials',
  ACC: 'Materials',
  BHARTIARTL: 'Communication',
  INDIGO: 'Industrials',
  IRCTC: 'Consumer Disc.',
  ZOMATO: 'Communication',
  NAUKRI: 'Communication',
  PAYTM: 'Technology',
  POLICYBZR: 'Financials',
  ADANIENT: 'Industrials',
  ADANIPORTS: 'Industrials',
};
