/** Representative S&P 500 ticker symbols (padded to 500 at generation time) */

export const SP500_TICKERS = [
  'AAPL', 'MSFT', 'AMZN', 'NVDA', 'GOOGL', 'GOOG', 'META', 'BRK.B', 'UNH', 'JNJ', 'XOM', 'JPM', 'V', 'PG', 'MA', 'HD', 'CVX', 'MRK', 'ABBV', 'LLY',
  'PEP', 'KO', 'COST', 'AVGO', 'WMT', 'MCD', 'CSCO', 'TMO', 'ACN', 'ABT', 'DHR', 'NEE', 'LIN', 'ADBE', 'CRM', 'NKE', 'TXN', 'PM', 'DIS', 'WFC',
  'BMY', 'RTX', 'ORCL', 'INTC', 'AMD', 'QCOM', 'UPS', 'HON', 'AMGN', 'IBM', 'LOW', 'SPGI', 'CAT', 'GE', 'BA', 'DE', 'SBUX', 'GS', 'BLK', 'INTU',
  'ISRG', 'AXP', 'MDT', 'GILD', 'AMAT', 'ADI', 'SYK', 'TJX', 'VRTX', 'REGN', 'LRCX', 'BKNG', 'PLD', 'MMC', 'CI', 'CB', 'SO', 'DUK', 'ZTS', 'MO',
  'CME', 'EQIX', 'CL', 'BDX', 'SHW', 'ITW', 'APD', 'EOG', 'SLB', 'PNC', 'USB', 'TGT', 'BSX', 'NOC', 'ICE', 'FCX', 'EMR', 'WM', 'NSC', 'GD',
  'MCO', 'AON', 'PSA', 'MAR', 'ECL', 'APH', 'SNPS', 'CDNS', 'KLAC', 'ADP', 'CMG', 'ORLY', 'ROP', 'TT', 'MSI', 'AJG', 'AFL', 'SRE', 'PCAR', 'AIG',
  'MET', 'TRV', 'ALL', 'PRU', 'HUM', 'ELV', 'CNC', 'MCK', 'CAH', 'COR', 'ABC', 'CVS', 'WBA', 'PFE', 'BIIB', 'MRNA', 'DXCM', 'IDXX', 'ALGN', 'MTD',
  'IQV', 'TECH', 'WAT', 'RMD', 'HOLX', 'PODD', 'ILMN', 'EXAS', 'VTRS', 'ZBH', 'BAX', 'HCA', 'DVA', 'UHS', 'THC', 'CERN', 'DGX', 'LH', 'A', 'ALB',
  'FMC', 'CF', 'MOS', 'NEM', 'NUE', 'STLD', 'X', 'CLF', 'AA', 'IP', 'PKG', 'WRK', 'SEE', 'BLL', 'AVY', 'EMN', 'LYB', 'DOW', 'DD', 'CE',
  'ETN', 'ROK', 'PH', 'AME', 'DOV', 'IR', 'GNRC', 'SWK', 'FAST', 'GWW', 'SNA', 'NDSN', 'IEX', 'PNR', 'XYL', 'FLS', 'ITT', 'RBC', 'GGG', 'AOS',
  'DAL', 'UAL', 'LUV', 'AAL', 'ALK', 'JBLU', 'SAVE', 'HA', 'SKYW', 'ALGT', 'FDX', 'CHRW', 'EXPD', 'JBHT', 'ODFL', 'XPO', 'KNX', 'SAIA', 'ARCB', 'WERN',
  'VZ', 'T', 'TMUS', 'CHTR', 'CMCSA', 'PARA', 'WBD', 'FOX', 'FOXA', 'NWSA', 'NWS', 'OMC', 'IPG', 'DISH', 'LUMN', 'FYBR', 'ATUS', 'CABO', 'SIRI', 'LBRDK',
  'NEE', 'DUK', 'SO', 'D', 'AEP', 'EXC', 'SRE', 'XEL', 'WEC', 'ES', 'ED', 'PEG', 'EIX', 'FE', 'PPL', 'AES', 'CNP', 'NI', 'LNT', 'EVRG',
  'AMT', 'CCI', 'SBAC', 'EQIX', 'PLD', 'PSA', 'SPG', 'O', 'WELL', 'AVB', 'EQR', 'DLR', 'VTR', 'ARE', 'MAA', 'UDR', 'ESS', 'CPT', 'INVH', 'SUI',
  'F', 'GM', 'RIVN', 'LCID', 'TSLA', 'STLA', 'HMC', 'TM', 'RACE', 'MBGAF', 'VWAGY', 'BMWYY', 'POAHY', 'DMLRY', 'HYMTF', 'NSANY', 'FUJHY', 'MZDAY', 'HOG', 'PII',
  'COIN', 'HOOD', 'SQ', 'PYPL', 'V', 'MA', 'DFS', 'SYF', 'COF', 'ALLY', 'C', 'BAC', 'WFC', 'JPM', 'GS', 'MS', 'SCHW', 'BLK', 'TROW', 'BEN',
  'NOW', 'SNOW', 'DDOG', 'NET', 'CRWD', 'ZS', 'PANW', 'FTNT', 'OKTA', 'MDB', 'TEAM', 'HUBS', 'VEEV', 'WDAY', 'ZM', 'DOCU', 'TWLO', 'U', 'PATH', 'PLTR',
  'NFLX', 'ROKU', 'SPOT', 'PINS', 'SNAP', 'MTCH', 'BMBL', 'IAC', 'ANGI', 'YELP', 'TRIP', 'EXPE', 'BKNG', 'ABNB', 'MAR', 'HLT', 'H', 'WH', 'PK', 'RHP',
  'KR', 'SYY', 'USFD', 'PFGC', 'CAG', 'GIS', 'K', 'CPB', 'SJM', 'HSY', 'MDLZ', 'KHC', 'TSN', 'HRL', 'SMPL', 'LANC', 'CALM', 'PPC', 'BG', 'ADM',
  'LMT', 'RTX', 'NOC', 'GD', 'BA', 'LHX', 'TDG', 'HII', 'TXT', 'HWM', 'CW', 'HEI', 'KTOS', 'AXON', 'LDOS', 'SAIC', 'CACI', 'BAH', 'PSN', 'KBR',
  'OXY', 'COP', 'EOG', 'PXD', 'DVN', 'FANG', 'MRO', 'APA', 'HES', 'OVV', 'CTRA', 'EQT', 'AR', 'RRC', 'CHK', 'SWN', 'CNX', 'MTDR', 'PR', 'SM',
  'UNP', 'CSX', 'NSC', 'CP', 'CNI', 'KSU', 'WAB', 'TRN', 'GBX', 'RAIL', 'ARCB', 'JBHT', 'KNX', 'ODFL', 'XPO', 'CHRW', 'EXPD', 'FDX', 'UPS', 'DAL',
  'TSLA', 'ENPH', 'SEDG', 'FSLR', 'RUN', 'NOVA', 'ARRY', 'CSIQ', 'JKS', 'DQ', 'MAXN', 'SPWR', 'BE', 'PLUG', 'BLDP', 'FCEL', 'BEEM', 'CHPT', 'EVGO', 'BLNK',
  'CRM', 'ORCL', 'SAP', 'ADBE', 'INTU', 'WDAY', 'NOW', 'SNOW', 'DDOG', 'MDB', 'TEAM', 'HUBS', 'VEEV', 'ZM', 'DOCU', 'TWLO', 'PATH', 'PLTR', 'AI', 'BBAI',
  'JPM', 'BAC', 'WFC', 'C', 'USB', 'PNC', 'TFC', 'SCHW', 'COF', 'AXP', 'DFS', 'SYF', 'ALLY', 'FITB', 'KEY', 'RF', 'CFG', 'HBAN', 'MTB', 'ZION',
  'PG', 'KO', 'PEP', 'CL', 'KMB', 'CHD', 'CLX', 'EL', 'COTY', 'REV', 'NWL', 'SPB', 'ENR', 'HELE', 'CENT', 'USNA', 'NUS', 'HLF', 'AVP', 'EPC',
  'MRNA', 'BNTX', 'NVAX', 'VRTX', 'REGN', 'BIIB', 'GILD', 'AMGN', 'BMY', 'PFE', 'JNJ', 'ABBV', 'LLY', 'MRK', 'AZN', 'NVO', 'SNY', 'GSK', 'TAK', 'TEVA',
];
